package forms;


import classes.Caesar;
import classes.ScreenCapture;
import panels.ImgPanel;
import com.sun.jna.platform.win32.WinDef;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import static java.lang.Thread.sleep;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RAVLYK
 */
public class FieldHolder extends javax.swing.JFrame {

    /**
     * Creates new form FeedHolder
     */
    
    Caesar caesar;
    Boolean isDraggable = false;
    int columnNumber = 2;
    
    
    public long makeLParam(int LoWord, int HiWord)
    {
        return (long)((HiWord << 16) | LoWord );
    }
    
    public FieldHolder() {
        initComponents();
        setLocationRelativeTo(null);
        

        /*WinDef.HWND hwnd = User32.INSTANCE.FindWindow("triuiScreen", "EVE - Dart Shikari");
        int WM_LBUTTONDOWN = 0x0201;
        int WM_LBUTTONUP = 0x0202;
        int WM_MOUSEMOVE = 0x0200;
        
        WinDef.WPARAM wparam = new WinDef.WPARAM();
        WinDef.LPARAM lparam = new WinDef.LPARAM();
        wparam.setValue(0);
        lparam.setValue(makeLParam(10,10));
        User32.INSTANCE.PostMessage(hwnd, WM_MOUSEMOVE, wparam, lparam);
        User32.INSTANCE.PostMessage(hwnd, WM_LBUTTONDOWN, wparam, lparam);
        User32.INSTANCE.PostMessage(hwnd, WM_LBUTTONUP, wparam, lparam);*/
        
    }
    
    public FieldHolder(Caesar caesar){
        this();
        this.caesar = caesar;
        createGameFields();
    }
    
    private void createGameFields(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlContainer = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        fieldsContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EVECeaser - Game Fields");

        jCheckBox1.setText("Accept drag");

        jLabel1.setText("Column number");

        jTextField1.setText("2");

        jButton1.setText("Submit");

        javax.swing.GroupLayout controlContainerLayout = new javax.swing.GroupLayout(controlContainer);
        controlContainer.setLayout(controlContainerLayout);
        controlContainerLayout.setHorizontalGroup(
            controlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(414, Short.MAX_VALUE))
        );
        controlContainerLayout.setVerticalGroup(
            controlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fieldsContainerLayout = new javax.swing.GroupLayout(fieldsContainer);
        fieldsContainer.setLayout(fieldsContainerLayout);
        fieldsContainerLayout.setHorizontalGroup(
            fieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        fieldsContainerLayout.setVerticalGroup(
            fieldsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fieldsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(controlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPanel1MouseClicked
        /*WinDef.HWND hwnd = User32.INSTANCE.FindWindow("triuiScreen", "EVE - Dart Shikari");
        int WM_LBUTTONDOWN = 0x0201;
        int WM_LBUTTONUP = 0x0202;
        int WM_MOUSEMOVE = 0x0200;
        
        WinDef.WPARAM wparam = new WinDef.WPARAM();
        WinDef.LPARAM lparam = new WinDef.LPARAM();
        wparam.setValue(0);
        lparam.setValue(makeLParam(evt.getX(),evt.getY()));
        User32.INSTANCE.PostMessage(hwnd, WM_MOUSEMOVE, wparam, lparam);
        try {
            sleep(50);
            User32.INSTANCE.PostMessage(hwnd, WM_LBUTTONDOWN, wparam, lparam);
            sleep(50);
            User32.INSTANCE.PostMessage(hwnd, WM_LBUTTONUP, wparam, lparam);
        } catch (InterruptedException ex) {
            Logger.getLogger(FieldHolder.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
    }//GEN-LAST:event_imgPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FieldHolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FieldHolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FieldHolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FieldHolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FieldHolder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlContainer;
    private javax.swing.JPanel fieldsContainer;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
