package forms;

import classes.Caesar;
import classes.Screen;
import classes.ScreenAreasPreset;
import classes.ScreenThreadReader;
import classes.ViewArea;
import classes.ViewPresets;
import com.sun.jna.Native;
import com.sun.jna.platform.win32.WinDef;
import com.sun.jna.win32.StdCallLibrary;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.HashMap;
import panels.ActiveWindowsPanel;
import panels.ScreenPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RAVLYK
 */
public class ScreenHolder extends javax.swing.JFrame {

    HashMap <String, ScreenPanel> screenPanels = new HashMap();
    Caesar caesar;
    
    public ScreenHolder() {
        initComponents();
        this.setLocationRelativeTo(null);
        screenScroll.setPreferredSize(new Dimension(410, 200));
        this.repaint();
        caesar = new Caesar();
        getActiveEveWindows();
    }
    
    public void setEveWindow(String windowName){
        ScreenPanel screenPanel = new ScreenPanel(windowName, this, caesar);
        this.screenContainer.add(screenPanel);
        screenPanels.put(windowName, screenPanel);
        repaintScreenPanels();
    }
    
    public void startAreaAdministrator(Screen screen, ScreenAreasPreset areasPreset){
        AreaAdministrator areaAdmin = new AreaAdministrator(screen, areasPreset.getName(), this);
        areaAdmin.setVisible(true);//.show();
    }
    
    public void removeScreenPanel(String panelName){
        this.screenContainer.removeAll();
        //screenPanels.get(panelName)
        screenPanels.remove(panelName);
        for(String key : screenPanels.keySet()){
            this.screenContainer.add(screenPanels.get(key));
        }
        repaintScreenPanels();
    }
    
    private void repaintScreenPanels(){
        int i = 0;
        for(String key : screenPanels.keySet()){
            screenPanels.get(key).setBounds(0, 200*i, 400, 200);
            i++;
        }
        this.screenContainer.setPreferredSize(new Dimension(500,200*screenPanels.size()));
        this.validate();
        this.repaint();
    }
    
    private void getActiveEveWindows(){
        
        ArrayList <String> windowNames = new ArrayList<>();
        
        User32.instance.EnumWindows(new WndEnumProc(){
        public boolean callback(WinDef.HWND hWnd, int lParam){   
            int size = 50;
            char[] className = new char[size];
            char[] windowName = new char[size];
            if(com.sun.jna.platform.win32.User32.INSTANCE.GetClassName(hWnd, className, size)!=0){
                if(String.valueOf(className).contains(Caesar.EVE_WINDOW_CLASS)){
                    com.sun.jna.platform.win32.User32.INSTANCE.GetWindowText(hWnd, windowName, size);
                    String resultName = "";
                    for(int i=0;i<windowName.length;i++){
                        resultName+=windowName[i];
                        if((i>1) && (windowName[i] == 0) && (windowName[i-1] == 0)){
                            resultName = resultName.substring(0, i-1);
                            break;
                        }
                    }
                    windowNames.add(resultName);
                }  
            }
            return true;
        }
        }, 0);
        
        windowsList.setListData(windowNames.toArray());
        windowsList.setSelectedIndex(0);
    }
    
    
    public static interface WndEnumProc extends StdCallLibrary.StdCallCallback {
        boolean callback (WinDef.HWND hWnd, int lParam);
    }
    
    public static interface User32 extends StdCallLibrary
    {
        final User32 instance = (User32) Native.loadLibrary ("user32", User32.class);
        boolean EnumWindows (WndEnumProc wndenumproc, int lParam);
        int GetClassName(WinDef.HWND hWnd, char[] lpClassName, int count);
        int GetWindowText(WinDef.HWND hWnd, char[] lpWindowName, int count);
        int GetTopWindow(WinDef.HWND hWnd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        screenScroll = new javax.swing.JScrollPane();
        screenContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        windowsList = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EVE Caesar - Sceen Holder");

        jButton2.setText("Load Feeds");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 25));

        screenScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        screenScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        screenContainer.setPreferredSize(new java.awt.Dimension(425, 200));

        javax.swing.GroupLayout screenContainerLayout = new javax.swing.GroupLayout(screenContainer);
        screenContainer.setLayout(screenContainerLayout);
        screenContainerLayout.setHorizontalGroup(
            screenContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        screenContainerLayout.setVerticalGroup(
            screenContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        screenScroll.setViewportView(screenContainer);

        jScrollPane1.setViewportView(windowsList);

        jButton3.setText("Add screen");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Refresh windows");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(screenScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(screenScroll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        setEveWindow(windowsList.getSelectedValue().toString());
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        getActiveEveWindows();
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenHolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenHolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenHolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenHolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenHolder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel screenContainer;
    private javax.swing.JScrollPane screenScroll;
    private javax.swing.JList windowsList;
    // End of variables declaration//GEN-END:variables
}
